### ISSUE TITLE
Fatal error: Cannot read property 'hardStop' of null

### ISSUE THREAD

**Issue by rvillanueva** [ericclemmons/grunt-express-server#105]
I couldn't quite isolate the cause, but sometimes my server would crash with the error

Fatal error: Cannot read property 'hardStop' of null

I'm guessing that sometimes options aren't passed through to the stop command.

**Comment by rvillanueva** [comment]
Pull request submitted with possible fix: #106

**Comment by jlsutherland** [comment]
That actually sounds just right. Maybe we should consider fixing this such that the default is `false`. What does your Gruntfile look like?

**Comment by jlsutherland** [comment]
Also thank you for the PR.  Though I may refactor a bit :)

**Comment by rvillanueva** [comment]
No prob!

Config: 
```
    express: {
      options: {
        port: process.env.PORT || 9000
      },
      dev: {
        options: {
          script: '<%= yeoman.server %>',
          debug: true
        }
      },
      prod: {
        options: {
          script: '<%= yeoman.dist %>/<%= yeoman.server %>'
        }
      }
    },

```
Watch:
```
      express: {
        files: ['<%= yeoman.server %>/**/*.{js,json}'],
        tasks: ['express:dev', 'wait'],
        options: {
          livereload: false,
          spawn: false //Without this option specified express won't be reloaded
        }
      },
```

**Comment by joshperry** [comment]
How can I get this to stop crashing my app? I've tried putting an explicit `hardStop: false` in all of the possible options hashes to no effect.

**Comment by jlsutherland** [comment]
Hi @joshperry, will you please post your gruntfile and grunt-express-server version?

**Comment by rvillanueva** [comment]
Hey Josh--if it helps, I was having crashes too but it wasn't actually related to grunt-express-server I think. If your problem looks like #107 , try upgrading your node version.

**Comment by joshperry** [comment]
Thanks @rvillanueva and @jlsutherland I'll take a look. #107 definitely looks promising!
