### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by Dakuan** [ericclemmons/grunt-express-server#14]
I'm getting an `Error: listen EADDRINUSE` error when using this module with watch.

This is my Gruntfile:

```
        watch: {
            all: {
                files: ['app/**/*.js', 'spec/**/*.js'],
                tasks: ['jshint', 'express']
            }
        },

        express: {
            dev: {
                options: {
                    script: 'app.js',
                    port: 9001
                }
            }
        }
```

**Comment by tarwich** [comment]
So... Sorry to resurrect a zombie, but just wanted to confirm that the problem is specifically this line from @meenie 
````js
grunt.registerTask('server', ['express:dev', 'watch']);
````

Which is fixed by removing the `express:dev` from boot and using `atBegin:true` as @eviljohnius mentioned in [comment #42258252](https://github.com/ericclemmons/grunt-express-server/issues/14#issuecomment-42258252)

**Comment by igrayson** [comment]
Looks like this could be a FAQ :)

I had this symptom when using babel-node to start an (ES6) server. I was using this configuration:

    dev: {
      options: {
        opts: ['node_modules/babel/bin/babel-node'],
        port: 8282,
        script: 'server.js'
      }
    }
  
After trying all other suggestions in this thread, I added a babel-node shim. This worked:

    dev: {
      options: {
        port: 8282,
        script: 'app.js'
      }
    }

app.js:
```javascript
require('babel/register')({stage: 0});
require('./server');
```

**Comment by ericclemmons** [comment]
Now that's interesting.  I expected the `babel-node` binary would work.
