### ISSUE TITLE
Server stops as soon as it starts

### ISSUE THREAD

**Issue by uorbe001** [ericclemmons/grunt-express-server#16]
I'm having a weird issue when running a server on the background. Running it on the foreground seems to work fine, but when I run it on the background the server starts and stops as soon as it is started (so it's pretty much useless). This is the output I get when running `grunt express:assets` with the background option set to true:

```
Running "express:assets" (express) task
Starting background Express server

Done, without errors.
Stopping Express server
```

As I said, running it on the foreground seems to work (but I really need it to run on the background as I want to start/stop that server surrounding another grunt task), but there is another issue with running it on the foreground if I try to stop it, I get:

```
Running "express:assets:stop" (express) task
Starting background Express server
Fatal error: listen EADDINUSE
```

I don't get why this seems to try to start the server, as far as I can tell from the code on the task it should simply kill the server if it was started? Does anyone know what I might be doing wrong?

**Comment by Agterra** [comment]
Hey, quite a bit late, but have you tried changing the port ? because the error code EADINUSE makes me think of that.
