### ISSUE TITLE
Can't run 'express' and 'watch' at the same time...

### ISSUE THREAD

**Issue by nicroto** [ericclemmons/grunt-express-server#74]
Hi,

I am having trouble getting express and watch running concurrently. The idea is to restart the server anytime the code has changed.

First of all, the express task doesn't start a server on port 5000. Why is that?
And secondly, watch can't be started after express begins.

Here is my watch and express configs and the composite task:

``` javascript
grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),

    ...

    watch: {
        client: {
            files: ['src/game/**/*', 'src/client/**/*'],
            tasks: ['devRebuild']
        },
        server: {
            files:  [ 'src/server/**/*', '!src/server/client/**/*' ],
            tasks:  [ 'express:server' ],
            options: {
                spawn: false
            }
        }
    },
    express: {
        options: {},
        server: {
            options: {
                script: 'src/server/server.js'
            }
        }
    }
});

// start develop
grunt.registerTask('devRebuild', ['clean', 'browserify:game_debug', 'stylus', 'copy']);
grunt.registerTask('dev', ['devRebuild', 'express', 'watch']);
```

And this is the server.js:

``` javascript
var pathUtils = require('path'),
    express = require("express"),
    bodyParser = require("body-parser"),
    app = express();

app.use( bodyParser.json() );

app.use( express.static( pathUtils.resolve( __dirname, "client" ) ) );

app.listen( process.env.PORT || 5000 );
```

And this is the output from running 'dev':

``` bash
$ grunt dev

Running "clean:all" (clean) task
>> 0 paths cleaned.

Running "browserify:game_debug" (browserify) task

Running "stylus:compile" (stylus) task
File src/server/client/css/main.css created.

Running "copy:main" (copy) task
Created 2 directories, copied 2 files

Running "express:server" (express) task
Starting background Express server
```

I think the problem comes from the inability to actually start the server -> then it can detect a server started -> can't move on to the next grunt task. But why doesn't it start the server?

Thanks.

**Comment by ismaels** [comment]
Hi guys, 
I just run into the same problem described here and even though I followed the instructions, I couldn't the it working. After a few cycles of trying and revising everything I found out that it does not work if you have background: false in you express task.

express: {
            dev: {
                options: {
                    port: 3000,
                    background: false,
                    script: './index.js'
                }
            }
        },
