### ISSUE TITLE
Looking for Contributors / Owners

### ISSUE THREAD

**Issue by ericclemmons** [ericclemmons/grunt-express-server#98]
(This is largely a copy/paste from ericclemmons/grunt-angular-templates#137)

First, I apologize that I can't spend any time on this project.

I haven't used Grunt since I switched to Gulp, and I stopped using _that_ nearly 2 years ago.

Plus, I have a family and a full-time job, so I'm not _really_ apologizing ;)

Therefore, **respond to this thread with the following info for Github & NPM publishing rights**:

1. Github username (well, it'll be on the issue, but just to show you're serious :D)
2. NPM email / user so I can give you `npm publisher` access.

If no one steps up, I'll mark this project as deprecated and let the community find alternatives.

**Comment by jlsutherland** [comment]
Happy to help out. :)

Github: jlsutherland
NPM: jls124@icloud.com / jlsutherland

**Comment by ericclemmons** [comment]
Yay!  Thanks @jlsutherland!  I also added @firstdoit & @paulpflug since they are pre-existing collaborators.

```
  npm owner ls
ericclemmons <eric@smarterspam.com>
firstdoit <gadr90@gmail.com>
jlsutherland <jls124@icloud.com>
paulpflug <paulpflugradt@googlemail.com>
```
